server:
  port: 8002
  servlet:
    context-path: /customers
spring:
  application:
    name: customer
  datasource:
    url: ${PG_CONNECTION_URL:jdbc:postgresql://localhost/customer}
    driver-class-name: org.postgresql.Driver
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: false
  kafka:
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      properties:
        value.serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: customer-service
      properties:
        value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        spring:
          deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted.packages: com.github.frederikpietzko.*
management:
  observations:
    annotations:
      enabled: true
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
