server:
  port: 8001
spring:
  application:
    name: order
  datasource:
    url: ${PG_CONNECTION_URL:jdbc:postgresql://localhost/order}
    driver-class-name: org.postgresql.Driver
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: false
  kafka:
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: restaurant-service
      properties:
        value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
otel:
  instrumentation:
    kafka:
      experimental-span-attributes: true