server:
  port: 8090
spring:
  application:
    name: gateway
gateway:
  services:
    order-service-url: http://localhost:8081
    restaurant-service-url: http://localhost:8000
    customer-service-url: http://localhost:8002
otel:
  sdk:
    disabled: true
